import { Product3D } from './product3DCatalog';

export const expandedProductCatalog: Product3D[] = [
  // FLOORING (10 products)
  { id: 'p3d-f01', name: 'Oak Hardwood - Natural', category: 'flooring', vendor: 'Premium Woods', price: 8.99, dimensions: { width: 0.127, height: 0.019, depth: 1.219 }, material: { baseColor: '#C19A6B', roughness: 0.6, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Natural Oak', installation: 'Nail-down', warranty: '50 years' }, marketplaceId: 'mp-f01' },
  { id: 'p3d-f02', name: 'Maple Engineered - Honey', category: 'flooring', vendor: 'Premium Woods', price: 7.25, dimensions: { width: 0.127, height: 0.012, depth: 1.219 }, material: { baseColor: '#D4A574', roughness: 0.5, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Honey Maple', installation: 'Click-lock', warranty: '35 years' }, marketplaceId: 'mp-f02' },
  { id: 'p3d-f03', name: 'Bamboo Strand - Carbonized', category: 'flooring', vendor: 'EcoFloors', price: 6.50, dimensions: { width: 0.127, height: 0.014, depth: 1.829 }, material: { baseColor: '#8B4513', roughness: 0.4, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Carbonized', installation: 'Floating', warranty: '25 years' }, marketplaceId: 'mp-f03' },
  { id: 'p3d-f04', name: 'Cork Flooring - Natural', category: 'flooring', vendor: 'EcoFloors', price: 5.75, dimensions: { width: 0.305, height: 0.012, depth: 0.305 }, material: { baseColor: '#C2B280', roughness: 0.8, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Natural Cork', installation: 'Glue-down', warranty: '20 years' }, marketplaceId: 'mp-f04' },
  { id: 'p3d-f05', name: 'Luxury Vinyl - Stone Look', category: 'flooring', vendor: 'FloorMaster Pro', price: 4.50, dimensions: { width: 0.305, height: 0.005, depth: 0.610 }, material: { baseColor: '#A9A9A9', roughness: 0.3, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Stone Texture', installation: 'Click-lock', warranty: '30 years' }, marketplaceId: 'mp-f05' },
  { id: 'p3d-f06', name: 'Laminate - Hickory', category: 'flooring', vendor: 'FloorMaster Pro', price: 3.25, dimensions: { width: 0.193, height: 0.008, depth: 1.219 }, material: { baseColor: '#B8956A', roughness: 0.6, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Hickory Print', installation: 'Click-lock', warranty: '25 years' }, marketplaceId: 'mp-f06' },
  { id: 'p3d-f07', name: 'Reclaimed Pine - Rustic', category: 'flooring', vendor: 'Heritage Woods', price: 12.99, dimensions: { width: 0.152, height: 0.019, depth: 1.829 }, material: { baseColor: '#8B7355', roughness: 0.7, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Distressed', installation: 'Nail-down', warranty: 'Lifetime' }, marketplaceId: 'mp-f07' },
  { id: 'p3d-f08', name: 'Concrete Polished', category: 'flooring', vendor: 'Industrial Floors', price: 15.00, dimensions: { width: 1.219, height: 0.102, depth: 1.219 }, material: { baseColor: '#808080', roughness: 0.2, metalness: 0.1 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Polished Concrete', installation: 'Pour & polish', warranty: '50 years' }, marketplaceId: 'mp-f08' },
  { id: 'p3d-f09', name: 'Epoxy Resin - Metallic', category: 'flooring', vendor: 'Industrial Floors', price: 18.50, dimensions: { width: 1.219, height: 0.003, depth: 1.219 }, material: { baseColor: '#4A4A4A', roughness: 0.1, metalness: 0.6 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Metallic Epoxy', installation: 'Pour & cure', warranty: '20 years' }, marketplaceId: 'mp-f09' },
  { id: 'p3d-f10', name: 'Rubber Gym Flooring', category: 'flooring', vendor: 'FitFloors', price: 6.99, dimensions: { width: 0.610, height: 0.019, depth: 0.610 }, material: { baseColor: '#2F4F4F', roughness: 0.9, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Textured Rubber', installation: 'Interlocking', warranty: '10 years' }, marketplaceId: 'mp-f10' },

  // TILE (10 products)
  { id: 'p3d-t01', name: 'Subway Tile - White', category: 'tile', vendor: 'TileWorld', price: 2.99, dimensions: { width: 0.076, height: 0.006, depth: 0.152 }, material: { baseColor: '#FFFFFF', roughness: 0.3, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Glossy', installation: 'Thin-set', warranty: 'Lifetime' }, marketplaceId: 'mp-t01' },
  { id: 'p3d-t02', name: 'Hexagon Tile - Marble', category: 'tile', vendor: 'TileWorld', price: 8.50, dimensions: { width: 0.254, height: 0.010, depth: 0.254 }, material: { baseColor: '#F8F8F0', roughness: 0.2, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Honed Marble', installation: 'Thin-set', warranty: 'Lifetime' }, marketplaceId: 'mp-t02' },
  { id: 'p3d-t03', name: 'Penny Round - Black', category: 'tile', vendor: 'Mosaic Masters', price: 15.99, dimensions: { width: 0.305, height: 0.006, depth: 0.305 }, material: { baseColor: '#000000', roughness: 0.1, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Glossy', installation: 'Mesh backing', warranty: '10 years' }, marketplaceId: 'mp-t03' },
  { id: 'p3d-t04', name: 'Wood-Look Plank Tile', category: 'tile', vendor: 'TileWorld', price: 5.75, dimensions: { width: 0.152, height: 0.008, depth: 0.914 }, material: { baseColor: '#8B7355', roughness: 0.6, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Matte Wood', installation: 'Thin-set', warranty: 'Lifetime' }, marketplaceId: 'mp-t04' },
  { id: 'p3d-t05', name: 'Terracotta - Rustic', category: 'tile', vendor: 'Mediterranean Tile', price: 7.25, dimensions: { width: 0.305, height: 0.019, depth: 0.305 }, material: { baseColor: '#E2725B', roughness: 0.7, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Natural', installation: 'Mortar', warranty: '50 years' }, marketplaceId: 'mp-t05' },
  { id: 'p3d-t06', name: 'Cement Tile - Patterned', category: 'tile', vendor: 'Artisan Tiles', price: 12.99, dimensions: { width: 0.203, height: 0.016, depth: 0.203 }, material: { baseColor: '#4682B4', roughness: 0.5, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Sealed Cement', installation: 'Thin-set', warranty: '25 years' }, marketplaceId: 'mp-t06' },
  { id: 'p3d-t07', name: 'Zellige - Handmade', category: 'tile', vendor: 'Moroccan Imports', price: 18.50, dimensions: { width: 0.102, height: 0.013, depth: 0.102 }, material: { baseColor: '#20B2AA', roughness: 0.4, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Glazed', installation: 'Thin-set', warranty: '15 years' }, marketplaceId: 'mp-t07' },
  { id: 'p3d-t08', name: 'Large Format - Concrete', category: 'tile', vendor: 'Modern Surfaces', price: 9.99, dimensions: { width: 0.610, height: 0.010, depth: 1.219 }, material: { baseColor: '#696969', roughness: 0.6, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Matte Concrete', installation: 'Large format mortar', warranty: 'Lifetime' }, marketplaceId: 'mp-t08' },
  { id: 'p3d-t09', name: 'Metal Tile - Copper', category: 'tile', vendor: 'Metal Works', price: 25.00, dimensions: { width: 0.305, height: 0.003, depth: 0.305 }, material: { baseColor: '#B87333', roughness: 0.3, metalness: 0.9 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Brushed Copper', installation: 'Adhesive', warranty: '20 years' }, marketplaceId: 'mp-t09' },
  { id: 'p3d-t10', name: 'Travertine - Tumbled', category: 'tile', vendor: 'Natural Stone Co', price: 11.50, dimensions: { width: 0.305, height: 0.013, depth: 0.305 }, material: { baseColor: '#D2B48C', roughness: 0.8, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Tumbled', installation: 'Thin-set', warranty: 'Lifetime' }, marketplaceId: 'mp-t10' },

  // COUNTERTOP (8 products)
  { id: 'p3d-c01', name: 'Marble - Carrara', category: 'countertop', vendor: 'Stone Masters', price: 95.00, dimensions: { width: 0.610, height: 0.030, depth: 0.762 }, material: { baseColor: '#F5F5F5', roughness: 0.15, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Polished Marble', installation: 'Professional', warranty: '25 years' }, marketplaceId: 'mp-c01' },
  { id: 'p3d-c02', name: 'Quartzite - White Macaubas', category: 'countertop', vendor: 'Stone Masters', price: 105.00, dimensions: { width: 0.610, height: 0.030, depth: 0.762 }, material: { baseColor: '#FFFAFA', roughness: 0.2, metalness: 0.1 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Polished', installation: 'Professional', warranty: '30 years' }, marketplaceId: 'mp-c02' },
  { id: 'p3d-c03', name: 'Soapstone - Black', category: 'countertop', vendor: 'Natural Stone Co', price: 75.00, dimensions: { width: 0.610, height: 0.030, depth: 0.762 }, material: { baseColor: '#2F4F4F', roughness: 0.6, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Oiled', installation: 'Professional', warranty: 'Lifetime' }, marketplaceId: 'mp-c03' },
  { id: 'p3d-c04', name: 'Concrete - Custom', category: 'countertop', vendor: 'Artisan Concrete', price: 120.00, dimensions: { width: 0.610, height: 0.051, depth: 0.762 }, material: { baseColor: '#808080', roughness: 0.4, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Sealed Concrete', installation: 'Custom pour', warranty: '15 years' }, marketplaceId: 'mp-c04' },
  { id: 'p3d-c05', name: 'Butcher Block - Maple', category: 'countertop', vendor: 'Wood Counters', price: 55.00, dimensions: { width: 0.610, height: 0.038, depth: 0.762 }, material: { baseColor: '#D4A574', roughness: 0.7, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Oiled Maple', installation: 'Professional', warranty: '10 years' }, marketplaceId: 'mp-c05' },
  { id: 'p3d-c06', name: 'Porcelain Slab - Marble Look', category: 'countertop', vendor: 'Modern Surfaces', price: 70.00, dimensions: { width: 0.610, height: 0.012, depth: 0.762 }, material: { baseColor: '#F0F0F0', roughness: 0.1, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Polished', installation: 'Professional', warranty: 'Lifetime' }, marketplaceId: 'mp-c06' },
  { id: 'p3d-c07', name: 'Recycled Glass - Vetrazzo', category: 'countertop', vendor: 'Eco Surfaces', price: 90.00, dimensions: { width: 0.610, height: 0.019, depth: 0.762 }, material: { baseColor: '#4682B4', roughness: 0.2, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Polished Glass', installation: 'Professional', warranty: '25 years' }, marketplaceId: 'mp-c07' },
  { id: 'p3d-c08', name: 'Solid Surface - Corian', category: 'countertop', vendor: 'DuPont Surfaces', price: 65.00, dimensions: { width: 0.610, height: 0.013, depth: 0.762 }, material: { baseColor: '#FFFFFF', roughness: 0.3, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Matte', installation: 'Professional', warranty: '10 years' }, marketplaceId: 'mp-c08' },

  // LIGHTING (12 products)
  { id: 'p3d-l01', name: 'Chandelier - Crystal', category: 'lighting', vendor: 'Luxury Lights', price: 899.00, dimensions: { width: 0.610, height: 0.914, depth: 0.610 }, material: { baseColor: '#FFD700', roughness: 0.1, metalness: 0.9 }, model: { type: 'primitive', primitive: 'cylinder' }, specs: { finish: 'Gold & Crystal', installation: 'Hardwired', warranty: '5 years' }, marketplaceId: 'mp-l01' },
  { id: 'p3d-l02', name: 'Track Lighting - Modern', category: 'lighting', vendor: 'LightCo', price: 199.99, dimensions: { width: 1.219, height: 0.076, depth: 0.076 }, material: { baseColor: '#000000', roughness: 0.4, metalness: 0.7 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Matte Black', installation: 'Track mount', warranty: '3 years' }, marketplaceId: 'mp-l02' },
  { id: 'p3d-l03', name: 'Under Cabinet LED Strip', category: 'lighting', vendor: 'LED Solutions', price: 49.99, dimensions: { width: 1.219, height: 0.013, depth: 0.025 }, material: { baseColor: '#FFFFFF', roughness: 0.5, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Aluminum', installation: 'Adhesive', warranty: '5 years' }, marketplaceId: 'mp-l03' },
  { id: 'p3d-l04', name: 'Sconce - Industrial', category: 'lighting', vendor: 'Vintage Lights', price: 129.00, dimensions: { width: 0.203, height: 0.305, depth: 0.254 }, material: { baseColor: '#8B4513', roughness: 0.6, metalness: 0.5 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Aged Brass', installation: 'Wall mount', warranty: '2 years' }, marketplaceId: 'mp-l04' },
  { id: 'p3d-l05', name: 'Floor Lamp - Arc', category: 'lighting', vendor: 'Modern Living', price: 349.00, dimensions: { width: 0.457, height: 2.134, depth: 0.457 }, material: { baseColor: '#C0C0C0', roughness: 0.3, metalness: 0.8 }, model: { type: 'primitive', primitive: 'cylinder' }, specs: { finish: 'Chrome', installation: 'Plug-in', warranty: '1 year' }, marketplaceId: 'mp-l05' },
  { id: 'p3d-l06', name: 'Smart Bulb - Color', category: 'lighting', vendor: 'SmartHome Tech', price: 29.99, dimensions: { width: 0.064, height: 0.114, depth: 0.064 }, material: { baseColor: '#FFFFFF', roughness: 0.4, metalness: 0.0 }, model: { type: 'primitive', primitive: 'sphere' }, specs: { finish: 'Frosted Glass', installation: 'Screw-in', warranty: '2 years' }, marketplaceId: 'mp-l06' },
  { id: 'p3d-l07', name: 'Vanity Light - 3-Light', category: 'lighting', vendor: 'Bath Lighting', price: 159.00, dimensions: { width: 0.610, height: 0.203, depth: 0.152 }, material: { baseColor: '#2F4F4F', roughness: 0.5, metalness: 0.6 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Oil Rubbed Bronze', installation: 'Wall mount', warranty: '3 years' }, marketplaceId: 'mp-l07' },
  { id: 'p3d-l08', name: 'Cove Lighting - LED', category: 'lighting', vendor: 'Architectural Lighting', price: 89.99, dimensions: { width: 2.438, height: 0.025, depth: 0.038 }, material: { baseColor: '#FFFFFF', roughness: 0.4, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Aluminum', installation: 'Recessed', warranty: '5 years' }, marketplaceId: 'mp-l08' },
  { id: 'p3d-l09', name: 'Outdoor Post Light', category: 'lighting', vendor: 'Exterior Lighting', price: 249.00, dimensions: { width: 0.305, height: 1.829, depth: 0.305 }, material: { baseColor: '#000000', roughness: 0.6, metalness: 0.4 }, model: { type: 'primitive', primitive: 'cylinder' }, specs: { finish: 'Powder Coated', installation: 'Post mount', warranty: '5 years' }, marketplaceId: 'mp-l09' },
  { id: 'p3d-l10', name: 'Rope Light - Flexible', category: 'lighting', vendor: 'LED Solutions', price: 34.99, dimensions: { width: 4.572, height: 0.013, depth: 0.013 }, material: { baseColor: '#FFD700', roughness: 0.3, metalness: 0.0 }, model: { type: 'primitive', primitive: 'cylinder' }, specs: { finish: 'Clear PVC', installation: 'Clips', warranty: '2 years' }, marketplaceId: 'mp-l10' },
  { id: 'p3d-l11', name: 'Skylight - Tubular', category: 'lighting', vendor: 'Natural Light Co', price: 499.00, dimensions: { width: 0.356, height: 1.219, depth: 0.356 }, material: { baseColor: '#E0E0E0', roughness: 0.1, metalness: 0.7 }, model: { type: 'primitive', primitive: 'cylinder' }, specs: { finish: 'Reflective Tube', installation: 'Roof mount', warranty: '10 years' }, marketplaceId: 'mp-l11' },
  { id: 'p3d-l12', name: 'Motion Sensor Light', category: 'lighting', vendor: 'Security Lighting', price: 79.99, dimensions: { width: 0.203, height: 0.152, depth: 0.127 }, material: { baseColor: '#FFFFFF', roughness: 0.5, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Weather Resistant', installation: 'Wall mount', warranty: '3 years' }, marketplaceId: 'mp-l12' },

  // FURNITURE (5 products)
  { id: 'p3d-fu01', name: 'Dining Table - Walnut', category: 'furniture', vendor: 'Fine Furniture', price: 1899.00, dimensions: { width: 2.134, height: 0.762, depth: 1.067 }, material: { baseColor: '#4A3728', roughness: 0.5, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Oiled Walnut', installation: 'Assembly', warranty: '5 years' }, marketplaceId: 'mp-fu01' },
  { id: 'p3d-fu02', name: 'Bookshelf - Industrial', category: 'furniture', vendor: 'Urban Living', price: 599.00, dimensions: { width: 1.219, height: 2.134, depth: 0.406 }, material: { baseColor: '#8B4513', roughness: 0.6, metalness: 0.5 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Wood & Metal', installation: 'Assembly', warranty: '2 years' }, marketplaceId: 'mp-fu02' },
  { id: 'p3d-fu03', name: 'Sofa - Mid-Century', category: 'furniture', vendor: 'Modern Living', price: 2499.00, dimensions: { width: 2.134, height: 0.864, depth: 0.914 }, material: { baseColor: '#4682B4', roughness: 0.7, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Velvet Upholstery', installation: 'Delivered', warranty: '10 years' }, marketplaceId: 'mp-fu03' },
  { id: 'p3d-fu04', name: 'Desk - Standing', category: 'furniture', vendor: 'Office Solutions', price: 799.00, dimensions: { width: 1.524, height: 1.219, depth: 0.762 }, material: { baseColor: '#FFFFFF', roughness: 0.4, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Laminate', installation: 'Assembly', warranty: '5 years' }, marketplaceId: 'mp-fu04' },
  { id: 'p3d-fu05', name: 'Bed Frame - Platform', category: 'furniture', vendor: 'Sleep Solutions', price: 1299.00, dimensions: { width: 1.930, height: 0.356, depth: 2.134 }, material: { baseColor: '#8B7355', roughness: 0.6, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Oak Veneer', installation: 'Assembly', warranty: '10 years' }, marketplaceId: 'mp-fu05' },

  // FIXTURES (5 products)
  { id: 'p3d-fx01', name: 'Bathroom Sink - Vessel', category: 'fixture', vendor: 'Bath Essentials', price: 299.00, dimensions: { width: 0.457, height: 0.152, depth: 0.457 }, material: { baseColor: '#FFFFFF', roughness: 0.1, metalness: 0.0 }, model: { type: 'primitive', primitive: 'cylinder' }, specs: { finish: 'Ceramic', installation: 'Counter mount', warranty: '5 years' }, marketplaceId: 'mp-fx01' },
  { id: 'p3d-fx02', name: 'Toilet - Dual Flush', category: 'fixture', vendor: 'Plumbing Pro', price: 449.00, dimensions: { width: 0.406, height: 0.762, depth: 0.711 }, material: { baseColor: '#FFFFFF', roughness: 0.2, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Vitreous China', installation: 'Floor mount', warranty: '10 years' }, marketplaceId: 'mp-fx02' },
  { id: 'p3d-fx03', name: 'Bathtub - Freestanding', category: 'fixture', vendor: 'Luxury Bath', price: 1899.00, dimensions: { width: 1.676, height: 0.610, depth: 0.762 }, material: { baseColor: '#FFFFFF', roughness: 0.1, metalness: 0.0 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Acrylic', installation: 'Freestanding', warranty: '15 years' }, marketplaceId: 'mp-fx03' },
  { id: 'p3d-fx04', name: 'Range Hood - Stainless', category: 'fixture', vendor: 'Kitchen Pro', price: 799.00, dimensions: { width: 0.914, height: 0.457, depth: 0.559 }, material: { baseColor: '#C0C0C0', roughness: 0.3, metalness: 0.9 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Stainless Steel', installation: 'Wall mount', warranty: '5 years' }, marketplaceId: 'mp-fx04' },
  { id: 'p3d-fx05', name: 'Door Handle Set - Modern', category: 'fixture', vendor: 'Hardware Plus', price: 89.99, dimensions: { width: 0.152, height: 0.076, depth: 0.064 }, material: { baseColor: '#2F4F4F', roughness: 0.4, metalness: 0.8 }, model: { type: 'primitive', primitive: 'box' }, specs: { finish: 'Matte Black', installation: 'Door mount', warranty: 'Lifetime' }, marketplaceId: 'mp-fx05' },
];

